export const ADD_ARTICLE = "ADD_ARTICLE"
export const ADD_LIKE = "ADD_LIKE"
export const FOUND_BAD_WORD = "FOUND_BAD_WORD"
export const REMOVE_LIKE = "REMOVE_LIKE"
export const DATA_LOADED = "DATA_LOADED"